### ISSUE TITLE
About model weights.

### ISSUE THREAD

**Issue by skye1210** [DonDominic/MP2Net#1]
Thanks for your wonderful work! I wonder if you can share the model weight for the SAT-MTB dataset. Thank you for considering my request!

**Comment by DonDominic** [comment]
We are sorry that due to code adjustments, there are currently bugs in multi-category tracking on the SatMTB dataset. I am actively working on refining this part and will release the training weights once it's done. In the meantime, the single-category tracking on the SatVideoDT dataset is functioning smoothly. Feel free to start exploring this feature! Thank you for your understanding and patience.

**Comment by DonDominic** [comment]
We are sorry that due to code adjustments, there are currently bugs in multi-category tracking on the SatMTB dataset. I am actively working on refining this part and will release the training weights once it's done. In the meantime, the single-category tracking on the SatVideoDT dataset is functioning smoothly. Feel free to start exploring this feature! Thank you for your understanding and patience.

> Thanks for your wonderful work! I wonder if you can share the model weight for the SAT-MTB dataset. Thank you for considering my request!

**Comment by DonDominic** [comment]
Hello, I have just released the model weights (DLADCN for now) and raw results for the SatMTB dataset. I hope this update serves you well.

**Comment by skye1210** [comment]
> Hello, I have just released the model weights (DLADCN for now) and raw results for the SatMTB dataset. I hope this update serves you well.

Thank you so much for sharing your great paper, code, and model weights! Your contribution is truly valuable to me, thanks a lot!!
